[package]
name = "pathway"
version = "0.7.2"
edition = "2021"
publish = false
rust-version = "1.72.0"
license = "BUSL-1.1"

[lib]
name = "pathway_engine"
crate-type = ["cdylib", "lib"]

[dev-dependencies]
assert_matches = "1.5.0"
eyre = "0.6.9"

[dependencies]
arc-swap = "1.6.0"
arcstr = { version = "1.1.5", default-features = false, features = ["serde", "std"] }
base32 = "0.4.0"
bincode = "1.3.3"
bitflags = { version = "2.4.1", features = ["std"] } # Hack to keep features unified between normal and dev deps
bytes = "1.5.0"
cfg-if = "1.0.0"
chrono = { version = "0.4.31", features = ["std", "clock"], default-features = false }
chrono-tz = "0.8.4"
crossbeam-channel = "0.5.8"
csv = "1.3.0"
derivative = "2.2.0"
differential-dataflow = { path = "./external/differential-dataflow" }
elasticsearch = "8.5.0-alpha.1"
futures = "0.3.29"
glob = "0.3.1"
hyper = { version = "0.14", features = ["server"] }
id-arena = "2.2.1"
itertools = "0.12.0"
jemallocator = { version = "0.5.4", features = ["stats", "disable_initial_exec_tls"] }
log = { version = "0.4.20", features = ["std"] }
ndarray = { version = "0.15.6", features = ["serde"] }
nix = { version = "0.27.1", features = ["fs", "user"] }
num-integer = "0.1.45"
numpy = "0.19.0"
once_cell = "1.18.0"
ordered-float = { version = "4.1.1", features = ["serde"] }
pipe = "0.4.0"
postgres = { version = "0.19.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
prometheus-client = "0.22.0"
pyo3 = { version = "0.19.2", features = ["abi3-py310", "multiple-pymethods"] }
pyo3-asyncio = "0.19.0"
pyo3-log = "0.9.0"
rand = "0.8.5"
rdkafka = { version = "0.36.0", features = ["ssl-vendored", "cmake-build", "zstd"] }
rusqlite = { version = "0.30.0", features = ["bundled"] }
rust-s3 = { version = "0.33.0", features = ["sync-native-tls-vendored", "sync-native-tls", "fail-on-err"], default-features = false }
scopeguard = "1.2.0"
send_wrapper = "0.6.0"
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = "3.4.0"
smallvec = { version = "1.11.2", features = ["union", "const_generics"] }
syn = { version = "2.0.39", features = ["default", "full", "visit", "visit-mut"] } # Hack to keep features unified between normal and build deps
tempfile = "3.8.1"
thiserror = "1.0.50"
timely = { path = "./external/timely-dataflow/timely", features = ["bincode"] }
tokio = "1.34.0"
xxhash-rust = { version = "0.8.7", features = ["xxh3"] }

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.10.2"

[features]
unlimited-workers = []

# Helpful for using external memory profilers
standard-allocator = []

# YOLO!
yolo-id64 = []
yolo-id32 = []

[profile.dev]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true

[build-dependencies]
pyo3-build-config = "0.19.2"
