[build-system]
requires = ["maturin >= 1.4"]
build-backend = "maturin"

[project]
name = "pathway"
requires-python = ">=3.10"
description = "Pathway is a data processing framework which takes care of streaming data updates for you."
readme = "README.md"
classifiers = [
    "License :: Other/Proprietary License",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "aiohttp >= 3.8.4",
    "click >= 8.1",
    "geopy >= 2.4.0",
    "h3 >= 3.7.6",
    "numpy >= 1.21",
    "pandas >= 1.3",
    "scikit-learn >= 1.0",
    "shapely >= 2.0.1",
    "sqlglot == 10.6.1",
    "numba >= 0.56; python_version < '3.12'",
    "pyarrow >= 10.0.0",
    "requests >= 2.31.0",
    "python-sat >= 0.1.8.dev",
    "beartype >= 0.14.0, < 0.16.0",
    "rich >= 12.6.0",
    "diskcache >= 5.2.1",
    "exceptiongroup >= 1.1.3; python_version < '3.11'",
    "boto3 >= 1.26.76",
    "google-api-python-client >= 2.108.0",
    "typing_extensions >= 4.8.0",
    "panel >= 1.3.1",
    "jupyter_bokeh >= 3.0.7",
    "jmespath >= 1.0.1",
    "Office365-REST-Python-Client >= 2.5.3",
    "aiohttp_cors >= 0.7.0",
    "opentelemetry-api >= 1.22.0",
    "opentelemetry-sdk >= 1.22.0",
    "opentelemetry-exporter-otlp-proto-grpc >= 1.22.0",
    "airbyte-serverless == 0.23",
    "fs >= 2.4.16",
    "async-lru >= 2.0.4",
]

[project.optional-dependencies]
tests = [
    "pytest >= 8.0.0, < 9.0.0",
    "pytest-xdist >= 3.3.1, < 4.0.0",
    "pytest-rerunfailures >= 13.0, < 14.0",
    "networkx",
    "python-louvain",
    "openapi_spec_validator",
    "openai >= 1.6",
    "kafka-python >= 2.0.2",
    "litellm >= 1.0",
    "llama_index >= 0.9, < 0.10",
    "tiktoken >= 0.5",
    "sentence_transformers",
    "transformers"
]

[project.urls]
"Homepage" = "https://pathway.com/"
"Source code" = "https://github.com/pathwaycom/pathway/"
"Documentation" = "https://pathway.com/developers/"
"Troubleshooting" = "https://pathway.com/troubleshooting/"

[project.scripts]
pathway = "pathway.cli:main"

[tool.maturin]
python-source = "python"
module-name = "pathway.engine"
features = ["pyo3/extension-module"]

[tool.mypy]
python_version = "3.11"
exclude = ["target", "examples", "python/pathway/tests", "integration_tests"]
ignore_missing_imports = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
